#!/usr/bin/env python3
"""Demo script showing how to import GLB files into Blender using Holodeck MCP tools."""

import json

def demo_glb_import():
    """Demonstrate GLB import workflow using Holodeck MCP tools."""

    print("=== Holodeck GLB Import Demo ===")
    print()

    # Sample GLB files (these would be generated by Holodeck's asset generation pipeline)
    sample_glb_files = [
        "workspace/sessions/2026-01-24T18-59-51Z_6c955af2/assets/obj_001.glb",
        "workspace/sessions/2026-01-24T18-59-51Z_6c955af2/assets/obj_001_0af12213.glb"
    ]

    print("Sample GLB files to import:")
    for i, glb_file in enumerate(sample_glb_files):
        print(f"  {i+1}. {glb_file}")
    print()

    # Step 1: Check Blender MCP connection
    print("Step 1: Check Blender MCP connection")
    print("Tool: mcp__blender__get_scene_info")
    print("Purpose: Verify Blender MCP is connected and ready")
    print()

    # Step 2: Generate import script
    print("Step 2: Generate Blender import script")
    script_content = generate_import_script(sample_glb_files, ["furniture_1", "furniture_2"])

    script_path = "glb_import_demo.py"
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(script_content)

    print(f"Generated script: {script_path}")
    print()

    # Step 3: Execute via MCP
    print("Step 3: Execute import via MCP")
    print("Tool: mcp__blender__execute_blender_code")
    print("Input:")
    print(json.dumps({
        "code": script_content[:200] + "..."  # Truncated for display
    }, indent=2))
    print()

    # Step 4: Verify import
    print("Step 4: Verify import results")
    print("Tool: mcp__blender__get_scene_info")
    print("Expected result: Scene should contain imported objects")
    print()

    # Step 5: Take screenshot
    print("Step 5: Capture result")
    print("Tool: mcp__blender__get_viewport_screenshot")
    print("Purpose: Capture visual confirmation of imported GLB files")
    print()

    print("=== Integration with Holodeck CLI ===")
    print("This functionality can be integrated into the Holodeck CLI as:")
    print()
    print("# Direct import command")
    print("holodeck import-glb --files assets/*.glb --names objects")
    print()
    print("# Part of build pipeline")
    print("holodeck build --request 'scene description'  # Automatically imports generated GLBs")
    print()
    print("# Part of edit pipeline")
    print("holodeck edit --session SESSION_ID 'replace object'  # Imports new GLB assets")
    print()

    return script_path

def generate_import_script(glb_files, object_names=None):
    """Generate Blender script to import GLB files."""

    import os
    script_lines = [
        "# GLB Import Script for Holodeck",
        "# Generated automatically",
        "",
        "import bpy",
        "import os",
        "from pathlib import Path",
        "",
        "def clear_scene():",
        "    \"\"\"Clear existing scene objects.\"\"\"",
        "    bpy.ops.object.select_all(action='SELECT')",
        "    bpy.ops.object.delete()",
        "",
        "def setup_scene():",
        "    \"\"\"Setup scene configuration.\"\"\"",
        "    bpy.context.scene.unit_settings.system = 'METRIC'",
        "    bpy.context.scene.unit_settings.scale_length = 1.0",
        "",
        "def import_glb_asset(glb_path, object_name=None):",
        "    \"\"\"Import a GLB asset into the scene.\"\"\"",
        "    if not os.path.exists(glb_path):",
        "        print(f'ERROR: GLB file not found: {glb_path}')",
        "        return None",
        "    ",
        "    try:",
        "        # Store previous selection",
        "        prev_selected = set(bpy.context.selected_objects)",
        "        ",
        "        # Import GLB using Blender's GLTF importer",
        "        bpy.ops.import_scene.gltf(filepath=glb_path)",
        "        ",
        "        # Get newly imported objects",
        "        new_objects = [obj for obj in bpy.context.selected_objects if obj not in prev_selected]",
        "        ",
        "        if new_objects:",
        "            root_object = new_objects[0]",
        "            if object_name:",
        "                root_object.name = object_name",
        "            print(f'SUCCESS: Imported {len(new_objects)} objects from {os.path.basename(glb_path)}')",
        "            return root_object",
        "        else:",
        "            print(f'WARNING: No objects imported from {glb_path}')",
        "            return None",
        "            ",
        "    except Exception as e:",
        "        print(f'ERROR: Failed to import {glb_path}: {e}')",
        "        return None",
        "",
        "def main():",
        "    print('=== Holodeck GLB Import Started ===')",
        "    ",
        "    # Setup scene",
        "    clear_scene()",
        "    setup_scene()",
        "    ",
        "    imported_objects = []"
    ]

    # Add import commands for each GLB file
    for i, glb_file in enumerate(glb_files):
        object_name = object_names[i] if object_names and i < len(object_names) else f"imported_object_{i+1}"

        script_lines.extend([
            f"    ",
            f"    # Import {os.path.basename(glb_file)}",
            f"    glb_path = r'{glb_file}'",
            f"    imported_obj = import_glb_asset(glb_path, '{object_name}')"
        ])

        if i == 0:
            script_lines.append(f"    if imported_obj:")
            script_lines.append(f"        imported_objects.append(imported_obj)")
            script_lines.append(f"        # Position first object at origin")
            script_lines.append(f"        imported_obj.location = (0, 0, 0)")
        else:
            script_lines.append(f"    if imported_obj:")
            script_lines.append(f"        imported_objects.append(imported_obj)")
            script_lines.append(f"        # Position subsequent objects with offset")
            script_lines.append(f"        imported_obj.location = ({i * 2.0}, 0, 0)")

    script_lines.extend([
        "",
        "    # Final report",
        "    mesh_objects = [obj for obj in bpy.data.objects if obj.type == 'MESH']",
        "    print(f'=== Import Completed ===')",
        "    print(f'Total mesh objects in scene: {len(mesh_objects)}')",
        "    print(f'Successfully imported: {len(imported_objects)} assets')",
        "    ",
        "    # Save scene",
        "    blend_path = 'imported_glb_scene.blend'",
        "    bpy.ops.wm.save_as_mainfile(filepath=blend_path)",
        "    print(f'Scene saved to: {blend_path}')",
        "",
        "if __name__ == '__main__':",
        "    main()"
    ])

    return "\n".join(script_lines)

if __name__ == "__main__":
    demo_glb_import()