# GLB Import Script
# Generated by Holodeck-Gemini

import bpy
import os

def clear_scene():
    """Clear existing scene objects."""
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()

def import_glb_asset(glb_path, object_name=None):
    """Import a single GLB asset."""
    if not os.path.exists(glb_path):
        print(f'GLB file not found: {glb_path}')
        return None
    
    # Store current selection
    prev_selected = set(bpy.context.selected_objects)

    try:
        # Import GLB
        bpy.ops.import_scene.gltf(filepath=glb_path)

        # Get newly imported objects
        new_objects = [obj for obj in bpy.context.selected_objects if obj not in prev_selected]
        
        if new_objects:
            # If multiple objects, use the first as root
            root_object = new_objects[0]
            if object_name:
                root_object.name = object_name
            print(f'Imported {len(new_objects)} objects from {glb_path}')
            return root_object
        else:
            print(f'No objects imported from {glb_path}')
            return None
            
    except Exception as e:
        print(f'Failed to import {glb_path}: {e}')
        return None

def setup_scene():
    """Setup basic scene configuration."""
    # Set units to metric
    bpy.context.scene.unit_settings.system = 'METRIC'
    bpy.context.scene.unit_settings.scale_length = 1.0
    
    # Add basic lighting if none exists
    if not bpy.data.lights:
        bpy.ops.object.light_add(type='SUN', location=(5, -5, 5))
        light = bpy.context.active_object
        light.data.energy = 2.0

def main():
    print('Starting GLB import...')
    
    # Clear scene
    clear_scene()
    setup_scene()
    
    # Import obj_001.glb
    glb_path_0 = r'C:\Users\Administrator\Desktop\holodeck-gemini\workspace\sessions\2026-01-24T18-59-51Z_6c955af2\assets\obj_001.glb'
    imported_obj_0 = import_glb_asset(glb_path_0, 'test_object_1')
    if imported_obj_0:
        print(f'Successfully imported as test_object_1')
    else:
        print(f'Failed to import obj_001.glb')
    
    # Import obj_001_0af12213.glb
    glb_path_1 = r'C:\Users\Administrator\Desktop\holodeck-gemini\workspace\sessions\2026-01-24T18-59-51Z_6c955af2\assets\obj_001_0af12213.glb'
    imported_obj_1 = import_glb_asset(glb_path_1, 'test_object_2')
    if imported_obj_1:
        print(f'Successfully imported as test_object_2')
    else:
        print(f'Failed to import obj_001_0af12213.glb')

    # Report final status
    total_objects = len([obj for obj in bpy.data.objects if obj.type == 'MESH'])
    print(f'Import completed. Total mesh objects in scene: {total_objects}')

    # Save scene
    blend_path = bpy.data.filepath or 'imported_glb_scene.blend'
    if not blend_path or blend_path == '':
        blend_path = 'imported_glb_scene.blend'
    bpy.ops.wm.save_as_mainfile(filepath=blend_path)
    print(f'Scene saved to: {blend_path}')

if __name__ == '__main__':
    main()