#!/usr/bin/env python3
"""Simple test script for GLB import functionality."""

import os
from pathlib import Path

def generate_glb_import_script(glb_paths, object_names=None):
    """Generate a Blender script to import GLB files.

    This is a standalone version of the GLB import functionality.
    """
    script_lines = [
        "# GLB Import Script",
        "# Generated by Holodeck-Gemini",
        "",
        "import bpy",
        "import os",
        "",
        "def clear_scene():",
        "    \"\"\"Clear existing scene objects.\"\"\"",
        "    bpy.ops.object.select_all(action='SELECT')",
        "    bpy.ops.object.delete()",
        "",
        "def import_glb_asset(glb_path, object_name=None):",
        "    \"\"\"Import a single GLB asset.\"\"\"",
        "    if not os.path.exists(glb_path):",
        "        print(f'GLB file not found: {glb_path}')",
        "        return None",
        "    ",
        "    # Store current selection",
        "    prev_selected = set(bpy.context.selected_objects)",
        "",
        "    try:",
        "        # Import GLB",
        "        bpy.ops.import_scene.gltf(filepath=glb_path)",
        "",
        "        # Get newly imported objects",
        "        new_objects = [obj for obj in bpy.context.selected_objects if obj not in prev_selected]",
        "        ",
        "        if new_objects:",
        "            # If multiple objects, use the first as root",
        "            root_object = new_objects[0]",
        "            if object_name:",
        "                root_object.name = object_name",
        "            print(f'Imported {len(new_objects)} objects from {glb_path}')",
        "            return root_object",
        "        else:",
        "            print(f'No objects imported from {glb_path}')",
        "            return None",
        "            ",
        "    except Exception as e:",
        "        print(f'Failed to import {glb_path}: {e}')",
        "        return None",
        "",
        "def setup_scene():",
        "    \"\"\"Setup basic scene configuration.\"\"\"",
        "    # Set units to metric",
        "    bpy.context.scene.unit_settings.system = 'METRIC'",
        "    bpy.context.scene.unit_settings.scale_length = 1.0",
        "    ",
        "    # Add basic lighting if none exists",
        "    if not bpy.data.lights:",
        "        bpy.ops.object.light_add(type='SUN', location=(5, -5, 5))",
        "        light = bpy.context.active_object",
        "        light.data.energy = 2.0",
        "",
        "def main():",
        "    print('Starting GLB import...')",
        "    ",
        "    # Clear scene",
        "    clear_scene()",
        "    setup_scene()"
    ]

    # Add import commands for each GLB file
    for i, glb_path in enumerate(glb_paths):
        object_name = object_names[i] if object_names and i < len(object_names) else f"imported_object_{i+1}"

        script_lines.extend([
            f"    ",
            f"    # Import {os.path.basename(glb_path)}",
            f"    glb_path_{i} = r'{glb_path}'",
            f"    imported_obj_{i} = import_glb_asset(glb_path_{i}, '{object_name}')",
            f"    if imported_obj_{i}:",
            f"        print(f'Successfully imported as {object_name}')",
            f"    else:",
            f"        print(f'Failed to import {os.path.basename(glb_path)}')"
        ])

    script_lines.extend([
        "",
        "    # Report final status",
        "    total_objects = len([obj for obj in bpy.data.objects if obj.type == 'MESH'])",
        "    print(f'Import completed. Total mesh objects in scene: {total_objects}')",
        "",
        "    # Save scene",
        "    blend_path = bpy.data.filepath or 'imported_glb_scene.blend'",
        "    if not blend_path or blend_path == '':",
        "        blend_path = 'imported_glb_scene.blend'",
        "    bpy.ops.wm.save_as_mainfile(filepath=blend_path)",
        "    print(f'Scene saved to: {blend_path}')",
        "",
        "if __name__ == '__main__':",
        "    main()"
    ])

    return "\n".join(script_lines)

def test_glb_import():
    """Test GLB import functionality."""

    # Find existing GLB files
    workspace_dir = Path("C:/Users/Administrator/Desktop/holodeck-gemini/workspace/sessions")
    glb_files = list(workspace_dir.rglob("*.glb"))

    if not glb_files:
        print("No GLB files found for testing")
        return

    # Take up to 2 GLB files for testing
    test_files = glb_files[:2]
    print(f"Found {len(test_files)} GLB files for testing:")
    for f in test_files:
        print(f"  - {f}")

    # Test 1: Generate script with automatic naming
    print("\n=== Test 1: Generate script with automatic naming ===")
    glb_paths = [str(f) for f in test_files]

    script_content = generate_glb_import_script(glb_paths)

    # Save script to file
    script_path = Path("test_import_auto.py")
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(script_content)

    print(f"Generated import script saved to: {script_path}")
    print(f"Script size: {len(script_content)} characters")

    # Test 2: Generate script with custom naming
    print("\n=== Test 2: Generate script with custom naming ===")
    custom_names = ["test_object_1", "test_object_2"]

    script_content2 = generate_glb_import_script(glb_paths, custom_names)

    # Save script to file
    script_path2 = Path("test_import_custom.py")
    with open(script_path2, 'w', encoding='utf-8') as f:
        f.write(script_content2)

    print(f"Generated import script with custom names saved to: {script_path2}")
    print(f"Script size: {len(script_content2)} characters")

    # Show usage instructions
    print("\n=== Usage Instructions ===")
    print("1. Manual execution:")
    print(f"   blender --python {script_path}")
    print(f"   blender --python {script_path2}")
    print()
    print("2. Via mcp__blender__execute_blender_code:")
    print("   Use the generated script content with the MCP tool")
    print()
    print("3. Via Holodeck CLI (when integrated):")
    print("   holodeck import-glb --files path1.glb path2.glb --names name1 name2")

    return script_path, script_path2

if __name__ == "__main__":
    test_glb_import()